AntmJS/vantui

packages/vantui/src/collapse/index.tsx
=> fix: 修复折叠面板不能放一个子元素的问题

packages/vantui/src/collapse/index.tsx, packages/vantui/src/dropdown-item/index.tsx
1. 修复了 DropdownItem change事件没有传递value
=> fix: DropdownItem change value

packages/vantui/package.json
rollup-plugin-styles 不知何处用到，暂时挪到 devDependencies
=> 移除无用的 dependencies

lerna.json
* 修复npm发布的时候少发了types文件夹 ([69b2847](https://github.com/AntmJS/vantui/commit/69b284700f4c27b17dd158e3f550ec69b6c7bd34))
* 初始化高度 ([#214](https://github.com/AntmJS/vantui/issues/214)) ([3bfc9b5](https://github.com/AntmJS/vantui/commit/3bfc9b5b20494a4232ee4460a94f6c543dd35f31))
* 更新弹窗动画 ([707d364](https://github.com/AntmJS/vantui/commit/707d36492a4ad83a13b92b184743ea7ca3366ff5))
* 修复编译commonjs失效的问题 ([36d2a80](https://github.com/AntmJS/vantui/commit/36d2a808afeb1381e7e5e1df19a5d4a36acd0060))
* 修复及优化组件 ([898fedc](https://github.com/AntmJS/vantui/commit/898fedc7b5e70fc98a567ef4ae1dc6c65cded78c))
* datetimePicker instance ([#215](https://github.com/AntmJS/vantui/issues/215)) ([4fe5627](https://github.com/AntmJS/vantui/commit/4fe5627fb7ee420113ffe558467ebfada2c4e7a1))
* table …
=> chore(release): publish 1.8.1

packages/vantui-demo/package.json, packages/vantui-demo/yarn.lock, packages/vantui-doc/src/datetime-picker/README.md, packages/vantui/src/datetime-picker/index.tsx, packages/vantui/src/field/index.tsx, packages/vantui/src/picker-column/index.tsx, packages/vantui/src/picker/index.tsx
field h5无法输入问题 （#267）
picker在 preact下的问题 （#200）
fix: value设置须晚于options设置 （#246）
=> fix: field h5问题

packages/vantui/src/field/index.tsx
=> fix: Field组件 type 为 textarea时，设置了 maxlength 后报错

lerna.json, packages/vantui-cli/package.json, packages/vantui-demo/package.json, packages/vantui-doc/package.json, packages/vantui/package.json
* 路由改为hash路由 ([e9fe926](https://github.com/AntmJS/vantui/commit/e9fe926fb97648b06124ebcf3419722ba4c51e0a))
* 修复文档生成异常 ([41b29fa](https://github.com/AntmJS/vantui/commit/41b29fa8de1778c799190655949b986f28c72fd9))
* 修复grid动态设置列数的问题 ([2d48724](https://github.com/AntmJS/vantui/commit/2d48724b0d54d31e5f0ddfa4bfe4bbb41a6c1c8e))
* 添加依赖包 ([81b372b](https://github.com/AntmJS/vantui/commit/81b372bd6bf180cecf6bc8fba9654b7d31477e84))
* 修复field样式问题 ([0b52375](https://github.com/AntmJS/vantui/commit/0b52375484355e5f903ddc926f0da623f5295bdb))
* 添加mini-nav-bar组件 ([ae4675d](https://github.com/AntmJS/vantui/commit/ae4675da0c4741f92887514fbb741bc47ebeee49))
* 折叠面板折叠动画时高度异常问题 ([#310](https://github.com/AntmJS/vantui/issues/310)) ([e5c43a5](https://github.com/AntmJS/vantui/commit/e5c43a522e11c0fc610e55475c74f2 …
=> chore(release): publish 1.9.19

lerna.json, packages/vantui-cli/package.json, packages/vantui-demo/package.json, packages/vantui-doc/package.json, packages/vantui/package.json
* 修复第1个tab激活的时候不展示高亮条 ([2cc0d5b](https://github.com/AntmJS/vantui/commit/2cc0d5b900dca26f4ae73550f33a86f1245383e4)), closes [#341](https://github.com/AntmJS/vantui/issues/341)
* 修复组件获取唯一key的时候有可能重复的问题 ([048b788](https://github.com/AntmJS/vantui/commit/048b7883c3f3e3ca5dfe5a054f316f9bf2ad3e0d))
* 修复powerscrollview内只有一个元素的时候展示empty的问题 ([a394213](https://github.com/AntmJS/vantui/commit/a3942137a3489d9b4f29d28bc79eb9de9e2e0219))
* 修复tabs动态添加tab的时候滚动条失效的问题 ([de16688](https://github.com/AntmJS/vantui/commit/de16688db787412aad2bbf004965b6c2daa5f8e1))
* 默认不再进行polyfill ([5cef4a8](https://github.com/AntmJS/vantui/commit/5cef4a89ad11bb56252771e067e45ff6433cc628))
* 添加模拟touch事件 ([36fff46](https://github.com/AntmJS/vantui/commit/36fff46e35d9231bb71155fc9e91dc6aecec23ee))
* 修复field value为0的时候不展示的问题 …
=> chore(release): publish 2.0.1

packages/vantui-doc/src/picker/README.md, packages/vantui/types/picker.d.ts
=> docs(picker): 优化picker组件 setIndexes文档参数

packages/vantui/src/calendar/index.tsx
- feat: 3.5版本scrollIntoView一直触发
=> feat: calendar3.5版本scrollIntoView一直触发

packages/vantui/src/button/index.less
=> fix: 增加button unclickable的限制

packages/vantui/src/table/index.tsx, packages/vantui/types/table.d.ts
为table增加了scrollViewProps的属性透传给ScrollView组件
- [] 错误修复(Bugfix) issue id #
=> feat: table增加scrollViewProps属性

packages/vantui/src/icon/wxs.ts, packages/vantui/types/icon.d.ts
=> feat: icon classPrefix 支持传空字符串去除前缀

packages/vantui/src/form-item/index.tsx, packages/vantui/src/form/core/formstore.ts
修复内容：label作为useDeepCompareEffect内存泄漏问题
修复方案：去掉label依赖，修改requiredMessageCallback的参数为fieldName
=> fix: 修复label作为useDeepCompareEffect内存泄漏问题

packages/vantui/src/count-down/index.tsx
解决countdown组件销毁时 错误时机获取tid 没有成功清除倒计时定时任务
=> fix(count-down): countdown组件销毁时 没有成功清除倒计时定时任务

packages/vantui/types/grid.d.ts
=> docs: 新增grid类型注释

lerna.json, packages/vantui-demo/package.json, packages/vantui/package.json
* 修复升级依赖导致的问题 ([659da4a](https://github.com/AntmJS/vantui/commit/659da4a4e30abc3eea601eb78789cc0d6b41e9a9))
* button组件plain样式修复（[#511](https://github.com/AntmJS/vantui/issues/511)） ([b479335](https://github.com/AntmJS/vantui/commit/b479335957f799974f6cdad586d05372bcdf35c6))
* dropDownMenu连续点击蒙层问题 ([bdd64f7](https://github.com/AntmJS/vantui/commit/bdd64f720b290367301fde9cad4d5ee48dd099d1))
* form组件validateTrigger设置的方法没有触发([#513](https://github.com/AntmJS/vantui/issues/513)) ([aae136b](https://github.com/AntmJS/vantui/commit/aae136b0c2fd0bc1460ed76d6668537521d55684))
* transiton组件导致页面无法滚动 ([cca011d](https://github.com/AntmJS/vantui/commit/cca011d893942bb9c9e0e1b094a5609e1cef32f7))
* 代码同步 ([337bbe0](https://github.com/AntmJS/vantui/commit/337bbe04deb54fb30d7a7a52d8bd5ce78460e6e0))
* 返回顶端逻辑修改 …
=> chore(release): publish 2.5.8

packages/vantui/src/circle/index.tsx, packages/vantui/types/circle.d.ts
=> feat: circle组件增加beginAngle

packages/vantui/src/dialog/index.tsx
解决问题 https://github.com/AntmJS/vantui/issues/537
=> fix: 小程序dialog使用input显示异常

packages/vantui/src/index-bar/index.tsx
=> fix: IndexBar scroll into view with offset

packages/vantui/src/tabs/index.tsx
=> style(tabs): remove console

packages/vantui/src/tabs/index.less
=> fix: tabs组件card模式下边框样式（#629）

packages/vantui/src/steps/README.md, packages/vantui/src/steps/demo/demo5.tsx, packages/vantui/src/steps/demo/index.tsx, packages/vantui/src/steps/index.tsx, packages/vantui/types/steps.d.ts
为 `Steps` 组件增加 `renderStep` 的 prop，允许使用者自定义每个步骤的渲染，另增加了对应的 demo 以及文档说明。
=> feat(Steps): add renderStep prop

packages/vantui/types/toast.d.ts
=> Docs toast

packages/vantui/types/tag.d.ts
=> docs: tag文档补全

packages/vantui/types/badge.d.ts
=> docs: badge文档补全

packages/vantui/types/steps.d.ts
=> docs: steps文档补全

packages/vantui/types/skeleton.d.ts
=> docs: skeleton文档补全

packages/vantui/src/search/index.tsx, packages/vantui/types/search.d.ts
=> docs: search文档补全

packages/vantui/src/button/index.less
- [ x] 错误修复(Bugfix) issue id #
=> mini button 没有定义line-height，导致文字不垂直居中

packages/vantui/src/swiper/swiper.tsx
=> fix: 修复离开swiper页面返回不滚动

packages/vantui/types/index-bar.d.ts
=> docs: indexBar文档补全

packages/vantui/src/dialog/demo/demo5.tsx, packages/vantui/src/dialog/demo/index.tsx
对dialog 组件文档新增了对 openType 的使用技巧 之前在使用的时候遇到了问题
=> docs(dialog): 添加 openType 属性说明和示例

packages/vantui/src/calendar/README.md, packages/vantui/src/calendar/index.less, packages/vantui/types/calendar.d.ts
- 扩展底部信息支持 ReactNode 类型，以增强组件灵活性 #684 ，bottomInfo、topInfo增加居中样式；
- 同步文档 API。
=> feat(calendar): 扩展日历组件的 bottomInfo 类型支持

packages/vantui/src/dropdown-menu/index.tsx
- 在 useLayoutEffect 中添加清理逻辑，确保在 children 更新时清理旧的子组件实例    #653 
新变动在本地测试可以实现子组件的动态更新：
不过也可以不改动代码，通过动态修改子组件的props来实现：
我不太清楚我的这个改动是否必要
=> feat(dropdown-menu): 优化 DropdownMenu 组件的子组件更新

packages/vantui/src/dialog/README.md, packages/vantui/src/dialog/demo/demo5.tsx
=> docs(Dialog): 完善对Dialog中使用openType的文档与示例
