- packages/vantui/src/components/nav-bar/wxs.ts
使用 navbar 的时候发现不管有没有设置 safeAreaInsetTop 都没有为状态栏预留高度，于是检查源码发现 navbar 状态栏高度的逻辑是引用同目录下的 wxs.ts ，但里面并没有对 navbar 传入的参数进行逻辑判断，便作此修改。
> fix: navbar 预留状态栏高度

- packages/vantui/src/toast/index.tsx
Toast控件事件监听事件在取消监听时没指定监听器实例，默认取消所有监听器
会导致父页面使用Toast控件，在跳转子页面并在其页面也同时使用Toast控件时，返回后所有监听器都被注销无法触发事件
> fix(Toast): off toast event listener need use its instance

- packages/vantui/types/tabbar.d.ts
TabbarItem的name属性是string | number，Tabbar的active属性是number，虽然active写string代码也能正常运行，但ts会报红，挺蛋疼的，所以就修复了下
> fix: tabbarprops active type

- packages/vantui/src/field/index.less
问题的原因是 `weui-input` 设置了 `height`，这个 `height` 应该根据我们自己组件的 `--cell-line-height` 值进行相应的调整
> fix: field input输入的内容在行内没有垂直居中的问题

- packages/vantui/src/nav-bar/mini.tsx
需求：根据页面滚动高度来调整`Navbar`的背景色和透明度。
修复的问题：原来 `getMiniNavbarHeight` 是采用 `useCallback` 来计算并返回结果，这个只有在第一次调用的时候才会触发，后期参数变化了，并没有触发的时机所以将 `useCallback` 替换成 `useMemo` ，它仅会在某个依赖项改变时才重新计算 `memoized` 值，这样就会根据用户动态传入的参数进行修改 `Navbar` 的样式。
> fix: navbar 在小程序中不能动态的修改样式问题

- packages/vantui/src/nav-bar/index.tsx
需求：根据页面滚动高度来调整`Navbar`的背景色和透明度。
修复的问题：原来 `getMiniNavbarHeight` 是采用 `useCallback` 来计算并返回结果，这个只有在第一次调用的时候才会触发，后期参数变化了，并没有触发的时机所以将 `useCallback` 替换成 `useMemo` ，它仅会在某个依赖项改变时才重新计算 `memoized` 值，这样就会根据用户动态传入的参数进行修改 `Navbar` 的样式。
> fix: navbar 在h5中不能动态的修改样式问题

- packages/vantui/src/collapse-item/animate.ts
- packages/vantui/src/collapse-item/index.tsx
问题：折叠面板所有动画，会以第一个面板内容的高度做动画，当有面板内容高度小于第一个内容时，这个面板的动画会有抽搐效果。
原因：原版中使用 `this` 获取 `context`保障获取到正确的元素高度，当前 `React` 版本中函数式写法无法使用 `this` 传递组件实例，传递了 `null` 之后所有子面板查询到的元素都是第一个面板。
解决思路：尝试使用 `refDOM`传递父元素也无法正确获取到面板元素，因此使用了随机类名以便强选择到正确元素。既然无法获取当前组件实例，便将 `setContentAnimate` 的第一个入参 `context` 改为了 `selector` 。
> fix: 折叠面板折叠动画时高度异常问题

- packages/vantui-doc/src/datetime-picker/README.md
- packages/vantui/types/datetime-picker.d.ts
**BUG 描述**
`DateTimePicker`的typing中，当`type`为`datetime`, `date`, `year-month`时，`value`应该接受`Date`类型
**修改方案**
修改`datetime-picker.d.ts`，`value`增加`Date`类型，同时修改说明文档
> fix: add Date type for value prop in DateTimePicker widget

- packages/vantui/src/col/index.tsx
- packages/vantui/src/col/wxs.ts
- packages/vantui/src/row/index.less
- packages/vantui/src/row/index.tsx
- packages/vantui/src/row/wxs.ts
- packages/vantui/types/col.d.ts
**原存在情况：**
Row 组件中 gutter 只能设置横向，  且没有向子Col 组件中传入 父级 gutter
**现修改情况：**
在Row组中 gutter 输入类型添加 数字数组 和 字符数组传入， 并允许使用 rpx 单位， 如：
`        <Row gutter={['50rpx', '50rpx']}>
<Col span={12}>
<View>hahaahha</View>
</Col>
<Col span={12}>
<View>hahaahha</View>
</Col>
<Col span={12}>
<View>hahaahha</View>
</Col>
<Col span={12}>
<View>hahaahha</View>
</Col>
<Col span={12}>
<View>hahaahha</View>
</Col>
<Col span={12}>
<View>hahaahha</View>
</Col>
</Row>`
> feat: 修改 Layout 布局中 横向和竖向 间隔

- packages/vantui/src/power-scroll-view/index.tsx
由于计算节点scrollOffset是耗时的，所以可能在第一次touchMove时拿不到touchStart的计算值
> 修正上滑误判断可能导致的刷新行为

- packages/vantui-cli/package.json
- packages/vantui/src/form-item/label.tsx
小程序的text只能嵌套自身，项目中label为非text的React.ReactNode时无法正常展示
> fix: 修改FormItem组件包裹label组件为View，解决label为非text的React.ReactNode时无法正常展示

- packages/vantui/src/nav-bar/index.tsx
修复了nav-bar组件使用state保存statusBarHeight并使用useEffect更新值导致部分机型例如14pro导航栏高度跳动。
> fix: 修复nav-bar不合适的获取statusBarHeight时机导致导航栏高度跳动

- packages/vantui/src/form-item/index.tsx
修复微信小程序中 FormItem 下输入框会闪现 Object Promise，对应 issue  #459 
> 修复微信小程序中 FormItem 下输入框会闪现 Object Promise 的问题

- packages/vantui/src/dialog/index.tsx
当自定义标题时，title 为 ReactNode，传入 bem 后 `JSON.stringify` 序列化会导致错误 。
复现： `<Dialog title={<View>自定义</View>} />`
> fix(dialog): 修复 dialog 组件自定义 title 时 h5 端报错问题

- packages/vantui/src/calendar/index.tsx
修复日历组件平铺模式下，设置`defaultDate` 时，无法滚动到默认日期下。
主要是两个闭包陷阱吧。 
第一个reset 方法，`setCurrentDate` 后，在 `scrollIntoViewFn` 中其实还没拿到对应的currentDate 值
第二个是在平铺模式下即`poppable = false`， useLayoutEffect `setCurrentDate` 后，下面的依赖于 `poppable 和`show`的useEffect 应该重新执行吧
> fix: 修改日历组件滚动bug

- packages/vantui/src/uploader/index.tsx
修复当onBeforeRead校验不通过时，onAfterRead依旧会被调用bug
- [ √] 错误修复(Bugfix) issue id #
- [ √] 提交到 main 分支
- [√ ] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [√ ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ √] 在本地测试可用，不会影响到其它功能
- [ √] 微信小程序
> 修复onBeforeRead返回false时，依旧调用onAfterRead上传bug

- packages/vantui/src/uploader/README.md
- packages/vantui/src/uploader/index.tsx
- packages/vantui/types/uploader.d.ts
为 `Uploader` 组件增加 `onClickUpload` 回调属性，在用户点击上传图标时触发回调。
* 缘由1：[VantUI 4](https://vant-ui.github.io/vant/#/zh-CN/uploader) 的 `Uploader` 组件中存在 `click-upload` 回调事件，此次 PR 为 `Uploader` 组件增加同效果的回调属性 `onClickUpload`。
* 缘由2：在进行视频上传的场景中（特别是在企业微信小程序中），拍摄时长为 60s 左右的视频并开启视频压缩 (`compressed`) 时，`Taro.chooseVideo` 方法的 `success` 回调会等待很长时间才会触发，导致用户上传视频后，需要等待很长时间才能够收到 `onBeforeRead` 和 `onAfterRead` 回调；因此，增加一个 `onClickUpload` 回调方法，以解决上述问题。
暂无。
> feat:为Uploader增加onClickUpload回调属性

- packages/vantui/src/uploader/index.tsx
修复Uploader组件在onBeforeARead中调用了callback(false)后依旧上传bug
- [ √] 错误修复(Bugfix) issue id #
- [ √] 提交到 main 分支
- [ √] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [ √] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [ √] 在本地测试可用，不会影响到其它功能
- [ √] 微信小程序
> fix:修复上传组件在onBeforeRead调用callback(false)时依旧会上传bug

- packages/vantui/src/calendar/index.tsx
日历组件开启 `allowSameDay`  开始结束日期无法默认选中同一日期
> fix: 修复日历组件的日期范围限制错误

- packages/vantui/src/icon/demo/demo2.tsx
- packages/vantui/src/icon/demo/demo3.tsx
- packages/vantui/src/icon/demo/demo4.tsx
- packages/vantui/src/icon/wxs.ts
**这个 PR 做了什么?** 
官网的icon点击之后可以让开发人员直接复制，而不用手动去写出name和icon组件
- [ √] 新功能(Feature)
- [ √] 提交到 main 分支
- [ √] Commit 信息遵循 [Angular Style Commit Message Conventions](https://gist.github.com/stephenparish/9941e89d80e2bc58a153)
- [√ ] 代码遵循相关包中的 .eslintrc, .tslintrc, .stylelintrc 所规定的规范
- [√ ] 在本地测试可用，不会影响到其它功能
> docs: 新增官方文档点击可以复制icon功能。

- packages/vantui/types/collapse.d.ts
> docs: collapse文档补全

- packages/vantui/types/radio.d.ts
> docs: radio文档补全

- packages/vantui/types/notice-bar.d.ts
> docs: noticeBar文档补全

- packages/vantui/src/checkbox/index.tsx
- packages/vantui/types/checkbox.d.ts
补充checkbox文档以及checkbox的index部分代码默认值补充，补充的默认值已确认不会影响其他功能
更新前
更新后
> docs: checkout文档补全以及代码优化补充

- packages/vantui/types/slider.d.ts
> docs: slider文档补全

- packages/vantui/src/calendar/index.tsx
将 catchMove 属性的值从直接使用变为根据 poppable 属性动态设置，避免开启平铺属性时，会阻碍页面滚动的问题
在平铺的日历组件上拖动页面会被阻塞，官网demo上即可复现
> fix(calendar): 修复日历组件的 catchMove 属性处理

- packages/vantui/src/swiper-item/index.tsx
- packages/vantui/src/swiper/swiper.tsx
- 修复 Swiper 组件在两个 item 时的 onChange 和 指示器样式错误问题
- 优化 SwiperItem 组件中 className 的 undefined 空值
有两张图片时，onChange返回的值有 0 1 2 3，且下面的指示器在 2 3 时没有选中
> fix(swiper): 修复 Swiper 组件在两个 item 时的 onChange 和 指示器样式错误问题

- packages/vantui/src/calendar/components/longSpan/index.tsx
- packages/vantui/src/calendar/index.less
- packages/vantui/src/calendar/index.tsx
- 在 LongSpan 组件中添加 ScrollView 组件，实现滚动功能
- 调整长跨度选择界面布局，优化用户体验
- 修复了一些样式问题，包括月份选择按钮样式和弹窗样式
添加滚动样式，防止溢出
> fix(calendar): 优化长跨度选择组件并添加滚动支持

- packages/vantui/src/common/utils.ts
- packages/vantui/src/common/version.ts
- packages/vantui/src/dropdown-item/index.tsx
- packages/vantui/src/image-cropper/index.tsx
- packages/vantui/src/mini-nav-bar/index.tsx
- packages/vantui/src/nav-bar/index.tsx
- packages/vantui/src/notify/notify.tsx
- packages/vantui/src/water-mark/utils.ts
- 新增 getWindowInfo 方法，用于获取窗口信息
- 更新 SDKversion 和 version 的获取方式
- 更新相关组件中获取窗口信息的方式，使用新的 getWindowInfo 方法
微信小程序开发工具一直报 getSystemInfoSync 这个API废弃。
不过除了支付宝小程序，目前我查到的几个小程序都没有微信小程序提供的`getWindowInfo`等替代`getSystemInfoSync`的 API。而 Taro 框架层面是直接替换 `Taro.xxx`为 `wx.xxx`  `my.xxx` 的，目前能想到的解决方式是只对`微信小程序`的`getSystemInfoSync`做单独处理。 不知道有没有更合适的处理方法
> refactor(utils): 对微信小程序 getSystemInfoSync API的废弃兜底

- packages/vantui/src/toast/README.md
- packages/vantui/src/toast/events.tsx
- packages/vantui/src/toast/index.tsx
- packages/vantui/types/toast.d.ts
- 补全 Toast 组件的默认配置相关功能  #730 
- 更新相关类型定义和文档说明
目前是模仿 vant-weapp 的实现，我不确定是否应该通过 @antmjs/vantui 的 DefaultProps 提供的 set 方法来实现。
> fix(toast): 补全 Toast 的默认配置相关功能

- packages/vantui/src/button/index.tsx
修复 Button 组件在 loadingMode 不是 toast 的情况下，loading 属性更新时会清理Toast 实例的问题
- 在 useEffect 中增加对 loadingMode 的判断，避免非 toast 模式下会清理任意 Toast 实例
- 更新 useEffect 的依赖项，确保在 loadingMode 或 innerLoading 变化时重新执行效果
> fix(button): 修复 Button 组件错误清理 Toast 的 bug
